### ISSUE TITLE
This does not work - am I using it wrong?

### ISSUE THREAD

**Issue by FraserElectronics** [peterblazejewicz/blazor-beforeunload#4]
I was hoping to use your component to catch when the browser window is closed so that I can clear some values in local storage in my web assembly project.
I initialise thus:
```
builder.Services.AddBeforeUnload();
```

Then in index.razor I do the following:

```
@code
{
    protected override void OnInitialized()
    {
        PageUnloaded.BeforeUnloadHandler += BeforeUnloadHandler;
    }

    public void Dispose()
    {
        PageUnloaded.BeforeUnloadHandler -= BeforeUnloadHandler;
    }

    public void BeforeUnloadHandler(object? sender, BeforeUnloadArgs args)
    {
        LocalStorage.RemoveItemAsync( "KeyName" );        
    }
}
```

If I set a breakpoint on all three methods, I get a breakpoint on OnInitialized when my application starts but don't get a breakpoint on Dispose nor BeforeUnloadHandler when the browser is closed.

Am I missing something?

Andy

**Comment by peterblazejewicz** [comment]
Hey, to be honest, this was not updated recently. Those handlers are called from JavaScript interop, so the first step is to make sure the .js code from package has been added to dotnet web app assets at runtime.

**Comment by FraserElectronics** [comment]
Okay, thanks.

Andy
